### PR TITLE
Added "Pressed" and "Hover" textures to the Top Bar buttons

### PR DESCRIPTION
**Pull request by YangTegap**
I have created hover and pressed textures for the minimize, maximize, and close buttons that matches the theme in both background color, border color, border thickness, and border radius.  With the hover background, the buttons do seem a little on the small side compared to the default window buttons, it may be worth increase the size and decreasing the spacing.  For now, I have kept everything set up the way it is.

### CODE REVIEW

**Comment by YangTegap** [comment]
A possible problem is that these buttons are set to 50% opacity under Visibility > Modulate.  While the background color is set to match the button theme of the startup panel, the color does appear slightly duller due to the transparency.  A possible solution would be to change the button color from white to the intended gray color, and restore the opacity to 100%.

**Comment by voylin** [comment]
Thanks for the pull request! We don't push directly to the master branch anymore, all changes should be pushed to the development branch first.

**Comment by aappaapp** [comment]
>We don't push directly to the master branch anymore, all changes should be pushed to the development branch first.

Maybe state that clearly in the `README.md` and `CONTRIBUTING.md` so this won't happen next time. So what should we do with this PR now?

**Comment by voylin** [comment]
> > We don't push directly to the master branch anymore, all changes should be pushed to the development branch first.
> 
> Maybe state that clearly in the `README.md` and `CONTRIBUTING.md` so this won't happen next time. So what should we do with this PR now?

Good idea! For now I'll be merging this pr and make the changes manually in the Development branch instead as there is no way to change the branch of this PR without causing issues. So overall not a big issue but was looking up what can be done about this in the future to avoid people pushing directly to master.

**Comment by voylin** [comment]
Made the changes in the development branch + made the default icons grey instead of setting the modulate to 126 for opacity. ;)

**Pull request merged**
